apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=ed6e87b45a4c6b4e5c515384ecdcf9d645b42f30
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/redhat-user-workloads/konflux-vanguard-tenant/konflux-operator
    newTag: on-pr-ed6e87b45a4c6b4e5c515384ecdcf9d645b42f30
