apiVersion: konflux.konflux-ci.dev/v1alpha1
kind: Konflux
metadata:
  name: konflux
spec:
  imageController:
    enabled: true
    spec:
      imageControllerManager:
        replicas: 1
        manager:
          resources:
            requests:
              cpu: 250m
              memory: 3Gi
            limits:
              cpu: 500m
              memory: 6Gi
